"""LlamaIndex schema definitions for SpyroSolutions"""

LLAMAINDEX_SCHEMA = """
Node properties (LlamaIndex format):
- **__Entity__:CUSTOMER**: name (STRING), industry (STRING), size (STRING), region (STRING)
- **__Entity__:PRODUCT**: name (STRING), type (STRING), description (STRING), features (LIST), market_focus (STRING)
- **__Entity__:SUBSCRIPTION**: product (STRING), value (STRING), start_date (DATE), end_date (DATE), status (STRING)
- **__Entity__:REVENUE**: amount (FLOAT), currency (STRING), period (STRING)
- **__Entity__:FEATURE**: name (STRING), description (STRING), category (STRING)
- **__Entity__:ROADMAP_ITEM**: title (STRING), description (STRING), priority (STRING), estimated_completion (DATE), status (STRING)
- **__Entity__:TEAM**: name (STRING), department (STRING), size (INTEGER), focus_area (STRING), velocity (INTEGER), capacity (INTEGER), utilization (FLOAT), revenue_supported (FLOAT)
- **__Entity__:PROJECT**: name (STRING), description (STRING), status (STRING), technologies (LIST), team_size (INTEGER), revenue_impact (FLOAT)
- **__Entity__:RISK**: type (STRING), description (STRING), severity (STRING), mitigation_strategy (STRING), status (STRING), probability (FLOAT)
- **__Entity__:OBJECTIVE**: title (STRING), description (STRING), target_date (DATE), progress (FLOAT), status (STRING)
- **__Entity__:CUSTOMER_SUCCESS_SCORE**: score (FLOAT), factors (LIST), trend (STRING), lastUpdated (DATETIME)
- **__Entity__:EVENT**: type (STRING), description (STRING), timestamp (DATETIME), impact (STRING), severity (STRING)
- **__Entity__:COST**: category (STRING), amount (FLOAT), frequency (STRING), department (STRING)
- **__Entity__:PROFITABILITY**: metric (STRING), value (FLOAT), period (STRING), trend (STRING)
- **__Entity__:FEATURE_PROMISE**: name (STRING), status (STRING), expected_date (DATE), delivery_date (DATE), created_date (DATE)
- **__Entity__:CONCERN**: type (STRING), description (STRING), priority (STRING), status (STRING), created_date (DATE), last_updated (DATETIME)
- **__Entity__:REGION**: name (STRING), code (STRING), currency (STRING)
- **__Entity__:REGIONAL_COST**: cost_multiplier (FLOAT), base_cost_per_customer (FLOAT), effective_date (DATE)
- **__Entity__:FEATURE_USAGE**: adoption_rate (FLOAT), value_score (FLOAT), active_users (INTEGER), last_updated (DATE), released_date (DATE)
- **__Entity__:SLA_PERFORMANCE**: month (DATE), metric (STRING), target (FLOAT), actual (FLOAT), met (BOOLEAN), penalty_applied (FLOAT)
- **__Entity__:COMPETITIVE_ADVANTAGE**: vs_industry (STRING), market_segment (STRING), created_date (DATE)
- **__Entity__:MARKET_SEGMENT**: name (STRING)
- **__Entity__:INDUSTRY_BENCHMARK**: cloud_uptime_sla (FLOAT), ai_accuracy_target (FLOAT), security_mttr_hours (FLOAT), updated_date (DATE)

Relationship properties:
- **SUBSCRIBES_TO**: revenue (STRING), contract_length (INTEGER), renewal_probability (FLOAT)
- **HAS_FEATURE**: importance (STRING), usage_frequency (STRING)
- **SUPPORTS**: alignment_score (FLOAT), priority (STRING)
- **AT_RISK**: likelihood (FLOAT), impact (STRING), identified_date (DATE)
- **USES**: satisfaction_score (FLOAT), usage_level (STRING)
- **GENERATES**: monthly_value (FLOAT), growth_rate (FLOAT)
- **INFLUENCED_BY**: impact_level (STRING), sentiment (STRING)
- **AFFECTS**: correlation_strength (FLOAT), impact_type (STRING)
- **IMPACTS**: severity (STRING), recovery_time (STRING)

The relationships are:
(:__Entity__:CUSTOMER)-[:SUBSCRIBES_TO]->(:__Entity__:SUBSCRIPTION)
(:__Entity__:PRODUCT)-[:HAS_FEATURE]->(:__Entity__:FEATURE)
(:__Entity__:TEAM)-[:SUPPORTS]->(:__Entity__:PRODUCT)
(:__Entity__:OBJECTIVE)-[:AT_RISK]->(:__Entity__:RISK)
(:__Entity__:CUSTOMER)-[:USES]->(:__Entity__:PRODUCT)
(:__Entity__:SUBSCRIPTION)-[:GENERATES]->(:__Entity__:REVENUE)
(:__Entity__:PRODUCT)-[:HAS_ROADMAP]->(:__Entity__:ROADMAP_ITEM)
(:__Entity__:TEAM)-[:WORKS_ON]->(:__Entity__:PROJECT)
(:__Entity__:CUSTOMER)-[:HAS_SUCCESS_SCORE]->(:__Entity__:CUSTOMER_SUCCESS_SCORE)
(:__Entity__:CUSTOMER_SUCCESS_SCORE)-[:INFLUENCED_BY]->(:__Entity__:EVENT)
(:__Entity__:COST)-[:AFFECTS]->(:__Entity__:PROFITABILITY)
(:__Entity__:RISK)-[:IMPACTS]->(:__Entity__:OBJECTIVE)
(:__Entity__:CUSTOMER)-[:HAS_FEATURE_PROMISE]->(:__Entity__:FEATURE_PROMISE)
(:__Entity__:CUSTOMER)-[:HAS_CONCERN]->(:__Entity__:CONCERN)
(:__Entity__:CUSTOMER)-[:LOCATED_IN]->(:__Entity__:REGION)
(:__Entity__:PRODUCT)-[:HAS_REGIONAL_COST]->(:__Entity__:REGIONAL_COST)
(:__Entity__:REGIONAL_COST)-[:IN_REGION]->(:__Entity__:REGION)
(:__Entity__:FEATURE)-[:HAS_USAGE]->(:__Entity__:FEATURE_USAGE)
(:__Entity__:CUSTOMER)-[:VALUES_FEATURE]->(:__Entity__:FEATURE)
(:__Entity__:SLA)-[:HAS_PERFORMANCE]->(:__Entity__:SLA_PERFORMANCE)
(:__Entity__:FEATURE)-[:PROVIDES_ADVANTAGE]->(:__Entity__:COMPETITIVE_ADVANTAGE)
(:__Entity__:COMPETITIVE_ADVANTAGE)-[:IN_SEGMENT]->(:__Entity__:MARKET_SEGMENT)
(:__Entity__:TEAM)-[:RESPONSIBLE_FOR]->(:__Entity__:ROADMAP_ITEM)
(:__Entity__:TEAM)-[:ADDRESSING]->(:__Entity__:CONCERN)
(:__Entity__:TEAM)-[:IMPROVES_SUCCESS]->(:__Entity__:CUSTOMER_SUCCESS_SCORE)
(:__Entity__:FEATURE_PROMISE)-[:DEPENDS_ON]->(:__Entity__:ROADMAP_ITEM)
(:__Entity__:PROJECT)-[:DEPENDS_ON]->(:__Entity__:PROJECT)
(:__Entity__:TEAM)-[:CREATES_RISK]->(:__Entity__:RISK)
(:__Entity__:CONCERN)-[:CREATES_RISK]->(:__Entity__:RISK)
(:__Entity__:RISK)-[:IMPACTS_SUCCESS]->(:__Entity__:CUSTOMER_SUCCESS_SCORE)
"""